### ISSUE TITLE
Establish code conventions

### ISSUE THREAD

**Issue by discapes** [zelbrium/gllabel#13]
So I'm making a branch that uses CMake, and I'm trying to make a well thought-out structure for the project there. One thing I need is some naming convention, for example the casing of filenames, { on newline? etc.. Right now it seems really mixed. Maybe make a CONTRIBUTING.md?

**Comment by azsn** [comment]
Yeah it's not good, I left this project a mess when I stopped working on it ~4 years ago >.< Right now I've been working to clean it up. So hopefully soon things will be much more consistent. `CONTRIBUTING.md` is a good idea though, I'll do that.

**Comment by azsn** [comment]
Added `CONTRIBUTING.md` in 3dfb480. Everything in the new files should follow it, but I think not everything in `label.cpp/hpp` does yet. Will be resolved as parts of it are getting rewritten.
