### ISSUE TITLE
Truckload of G++ errors

### ISSUE THREAD

**Issue by discapes** [zelbrium/gllabel#14]
![pic-selected-201004-1804-51](https://user-images.githubusercontent.com/48839377/95019130-565b7100-066c-11eb-9754-ca16d4d90af2.png)
tryna fix...

**Comment by azsn** [comment]
Ah sorry! The screenshot is too low res for me to be able to read any of those errors, but hopefully I just fixed a bunch of them in the commit I just made. See the commit I made here for details: https://github.com/zelbrium/gllabel/pull/15#issuecomment-703282170
