### ISSUE TITLE
Hacktoberfest participation?

### ISSUE THREAD

**Issue by discapes** [zelbrium/gllabel#17]
https://hacktoberfest.digitalocean.com/hacktoberfest-update
Because some idiots created spammy pull requests to get a T-shirt, they made the whole event opt-in for maintainers. So if you want to participate, you should add the `hacktoberfest` topic to the repo, and maybe someone will contribute.

**Comment by azsn** [comment]
Sure, did it. Having lots of people try to contribute will stress me out so I might have to remove it if that becomes a problem.
