### ISSUE TITLE
GlyphVertex v[6]; 

### ISSUE THREAD

**Issue by pazduha** [zelbrium/gllabel#2]
Inside label.cpp I added:
GlyphVertex v[6]; // Insertion code depends on v[0] equaling appendOffset (therefore it is also set before continue;s above)
v[0].pos = glm::vec2(0, 0); //new

**Comment by azsn** [comment]
Thanks! Fixed in 8294a4d. Somehow it worked without that on my machine. (All of this code is a mess and I've been meaning to clean it up since the moment I wrote it...)

**Comment by pazduha** [comment]
No problem. Thanks for the code!
