### ISSUE TITLE
Makefile is wacky

### ISSUE THREAD

**Issue by stacksmith** [zelbrium/gllabel#3]
This took me way too long to figure out as I am a Lisp guy and naturally despise makefiles and such...  The makefile fails with a shid of 'undefined reference' errors from ld.  But moving cpp files forward makes it work on my linux box...
g++ -Wall -g -o demo  demo.cpp label.cpp -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/GLFW -I/usr/include/GL -lGLEW -lGLU -lGL -lglfw -lfreetype

**Comment by azsn** [comment]
Thanks! Your g++ invocation is correct, `-l` is supposed to go after the files. The way I had it will still work correctly on some g++ implementations but not others, I'm not sure why. Sorry it took me so long to get to your comment.
